[package]
name = "factorio_verify"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "<=1.0.171"
base64 = "0.21.2"
graphviz-rust = "0.6.6"
inflate = "0.4.5"
petgraph = "0.6.4"
relations = "0.3.0"
serde = { version = "1.0.164", features = ["derive"] }
serde_json = "1.0.99"
serde_repr = "0.1.12"
z3 = "0.12.1"
